export * from './Repositories'
export * from './Defaults'
export * from './About_Texts'
export * from './Hero_Texts'
export * from './Nav_Texts'
export * from './Projects_Texts'
export * from './Tech_Texts'
